apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallagher-mhp-backend
  namespace: gallagher-mhp-staging
  labels:
    app: gallagher-mhp
    component: backend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gallagher-mhp
      component: backend
  template:
    metadata:
      labels:
        app: gallagher-mhp
        component: backend
        environment: staging
    spec:
      containers:
        - name: backend
          image: <registry>/gallagher-mhp-backend:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          
          env:
            # From ConfigMap
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: gallagher-mhp-config
                  key: ENVIRONMENT
            - name: API_V1_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: gallagher-mhp-config
                  key: API_V1_PREFIX
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: gallagher-mhp-config
                  key: LOG_LEVEL
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: gallagher-mhp-config
                  key: CORS_ORIGINS
            
            # From Secrets
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gallagher-mhp-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gallagher-mhp-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: gallagher-mhp-secrets
                  key: REDIS_URL
            - name: SOCRATA_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gallagher-mhp-secrets
                  key: SOCRATA_APP_TOKEN
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: gallagher-mhp-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gallagher-mhp-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: gallagher-mhp-secrets
                  key: SENTRY_DSN
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: gallagher-mhp-secrets
                  key: SLACK_WEBHOOK_URL
          
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          
          livenessProbe:
            httpGet:
              path: /api/v1/health/liveness
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /api/v1/health/readiness
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]

---
apiVersion: v1
kind: Service
metadata:
  name: gallagher-mhp-backend
  namespace: gallagher-mhp-staging
  labels:
    app: gallagher-mhp
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: gallagher-mhp
    component: backend

