---
# Prometheus Configuration for GallagherMHP

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    cluster: 'gallagher-mhp-prod'
    env: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load alerting rules
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # GallagherMHP Backend API
  - job_name: 'gallagher-mhp-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'backend:8000'
    scrape_interval: 15s
    scrape_timeout: 10s
    
  # Health Probes
  - job_name: 'readiness-probe'
    metrics_path: '/api/v1/health/readiness'
    static_configs:
      - targets:
          - 'backend:8000'
    scrape_interval: 10s
    
  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets:
          - 'postgres-exporter:9187'
    
  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'
    
  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'

