name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_DB: gallagher_mhp_test
          POSTGRES_USER: gallagher
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with ruff
      working-directory: ./backend
      run: |
        pip install ruff
        ruff check app/
    
    - name: Type check with mypy
      working-directory: ./backend
      run: |
        pip install mypy
        mypy app/ --ignore-missing-imports || true
    
    - name: Run tests
      working-directory: ./backend
      env:
        DATABASE_URL: postgresql://gallagher:test_password@localhost:5432/gallagher_mhp_test
        REDIS_URL: redis://localhost:6379
        SECRET_KEY: test-secret-key-for-ci
      run: |
        pytest --cov=app --cov-report=xml --cov-report=term
    
    - name: Check migration drift
      working-directory: ./backend
      env:
        DATABASE_URL: postgresql://gallagher:test_password@localhost:5432/gallagher_mhp_test
        REDIS_URL: redis://localhost:6379
        SECRET_KEY: test-secret-key-for-ci
      run: |
        alembic revision --autogenerate -m "drift-check"
        generated=$(ls alembic/versions/*drift_check*.py 2>/dev/null || true)
        if [ -n "$generated" ]; then
          ALEMBIC_GENERATED="$generated" python <<'PY'
import ast
import os

path = os.environ["ALEMBIC_GENERATED"]
with open(path, "r", encoding="utf-8") as fh:
    module = ast.parse(fh.read())

def has_ops(fn):
    return not (len(fn.body) == 1 and isinstance(fn.body[0], ast.Pass))

status = 0
for node in module.body:
    if isinstance(node, ast.FunctionDef) and node.name in {"upgrade", "downgrade"}:
        if has_ops(node):
            status = 1
            break

raise SystemExit(status)
PY
          status=$?
          if [ $status -ne 0 ]; then
            echo "Schema drift detected. Generate a new Alembic revision."
            git --no-pager diff "$generated"
            rm -f "$generated"
            exit 1
          fi
          rm -f "$generated"
        fi

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./backend/coverage.xml
        flags: backend

  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Cache Node modules
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Lint
      working-directory: ./frontend
      run: npm run lint
    
    - name: Type check
      working-directory: ./frontend
      run: npm run type-check
    
    - name: Build
      working-directory: ./frontend
      run: npm run build
